### ISSUE TITLE
Allow nil for payloads

### ISSUE THREAD

**Issue by Tieske** [Tieske/binaryheap.lua#12]
requires additional tests, and no length checking on the `payload` table as it is no longer a valid list/array

**Comment by starius** [comment]
I see the following problems:
- `nil` can not be a key of a table, so `heap.reverse` wont work
- `nil` is returned from methods like `pop` and `peek` when no value exists. If we allow nil as a valid payload, then this behaviour is to be changed
- using `nil` as a valid valud is not Lua-ish

:-1:

**Comment by Tieske** [comment]
The idea was to use the same implementation for a heap with payload as one without a payload (in the latter case payload == nil)

> nil  can not be a key of a table, so  heap.reverse  wont work

if you test for nil first... just return nil

> using  nil  as a valid valud is not Lua-ish

it is for omitting parameters

but as noted in my initial posting, it does have some issues... don't know the performance impact of those

**Comment by starius** [comment]
> The idea was to use the same implementation for a heap with payload as one without a payload (in the latter case payload == nil)

I think, type of a heap should be determined when a heap is created. Otherwise, how to deal with same heap being used as both plain heap and unique heap?

**Comment by Tieske** [comment]
@starius re reading this, I think it is indeed not a good idea. Closing.
