### ISSUE TITLE
field "reverse"

### ISSUE THREAD

**Issue by starius** [Tieske/binaryheap.lua#5]
[The documentation](http://tieske.github.io/binaryheap.lua/index.html) mentions field "reverse", which does not exist. There are fields "value" and "reverse". I think, they should be renamed to "value**s**" and "reverse".

**Comment by starius** [comment]
Oops, I misread the documentation. Field "reverse" != field "payload".

What to do with fields, in my opinion:
- [ ] All 3 fields should be documented in main part of the documentation.
- [x] Field "payload" should not be created in plain heaps.
- [ ] Field "value" should be renamed to "values", field "payload" to "payloads".

**Comment by Tieske** [comment]
not a big enough issue to warrant a change, but then again it's still under development, so fine by me.
