### ISSUE TITLE
how to remove by pos in unique heap?

### ISSUE THREAD

**Issue by starius** [Tieske/binaryheap.lua#7]
Method `remove` behaves in different way in plain heap and in unique heap. I think it should be replaced with two methods:
- `removePos(pos)`
- `removePayload(payload)`

These two methods are better than ambigous `remove` method.

Same considerations for `update` method.

**Comment by Tieske** [comment]
Why would we need remove by pos? For completeness I follow, but I don't see a usecase.

In unique heap everything is done by `payload` that's the whole idea of the reverse lookup.

**Comment by starius** [comment]
Removing by pos is faster. If we need to remove an element with known pos, we can do this directly.

Usecase:

``` lua
payload = ...
pos = heap.reverse[payload]
value = heap.value[pos]
if value < 100 then
  heap:removePos(pos)
  -- or heap:removePayload(payload)
end
```

However the impact of one table indexing is negligible. I can't detect advantage of `removePos` in my benchmark. That is why I close the issue.
