### ISSUE TITLE
we need unique heap subtype where payload=value

### ISSUE THREAD

**Issue by starius** [Tieske/binaryheap.lua#8]
It is actually a plain heap with map from values to positions. This if often needed.

**Comment by Tieske** [comment]
But then we reduce everything to a single heap, with a reverse lookup.... no?

WHat type of heaps would be required;
1. plain heap, no reverse, no payload
2. plain heap, with reverse, no payload
3. both again, but with payload (or just the plain one, with payload being optional (nil allowed))

I think it requires some profiling, to see what the performance impact is of adding 2 and 3 on top of 1.

**Comment by starius** [comment]
For profiling we need code examples, which can be used to measure time. I have implemented Dijkstra's algorithm in #11. Number of columns and rows can be increased to convert it into a benchmark. There is also implementation of the algorithm mentioned in #9.

**Comment by Tieske** [comment]
@starius do you feel like still pursuing this, or shall we close it?

**Comment by starius** [comment]
@Tieske I don't need it. We can close.
