### ISSUE TITLE
remove, pop and peek results order

### ISSUE THREAD

**Issue by starius** [Tieske/binaryheap.lua#9]
Method `remove` returns (payload, value).
Method `pop` returns (payload, value).
Method `peek` returns (value, payload).

I think, all these methods should return (value, payload), because all heaps have values, but some heaps do not have payloads.

**Comment by Tieske** [comment]
This is on purpose. I intended it for timers, in which case when you pop/remove an item, the `value` is no longer of interest, only the payload. Except when using peek, the n you need the value to check whether the timeout is due.
In cases where the information is carried only by the `value`, there is no need for a peek function imo.

**Comment by starius** [comment]
> I intended it for timers, in which case when you pop/remove an item, the value is no longer of interest, only the payload. Except when using peek, the n you need the value to check whether the timeout is due.

Binary heaps can be used not only for timers (see my use case below). Anyway, `pop` returing results in another order than `peek` is very confusing, in my opinion. Replacing `pop` with `peek` requires changing variables to which results are stored. This will cause mistakes when `pop` is replaced with `peek` and vice versa. It actually did cause mistakes in my code, which were hard to find, that is why I opened this issue.

> In cases where the information is carried only by the value, there is no need for a peek function imo.

Here is a problem which can be solved using plain heap and in which `peek` is needed.

> There is an array a on N numbers: a[1](https://en.wikipedia.org/wiki/Dynamic_programming), a[2], ..., a[N]. Function b(i) is as follows: b(0) = 0, b(i) = a[i] + min(b(i - M), b(i - M + 1), ..., b(i - 1)). (Members with negative array indices are ecluded from this formula.) M is known to be less than N. Calculate b(N).

This problem can be solved in time O(N log M) by solving it for i from 1 to N ([Dynamic programming](https://en.wikipedia.org/wiki/Dynamic_programming)). Binary heap stores last M values of b(i). We need peek at each step. It can not be replaced with pop, because we start with empty heap, let it grow to size M and only after this start popping.

**Comment by Tieske** [comment]
Ok! let's do the value+payload approach. Indeed not all heaps have payloads, and because it is the same order on entry into the heap (insert)
